FROM ruby:3.2.2
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.js + 必要なパッケージをインストール
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
&& apt update -qq \
&& apt install -y build-essential postgresql-client nodejs \
&& npm install --global yarn

WORKDIR /app

# Gemfileをコピーしてbundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションファイルをコピー
COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]